---
- role: "Challenge and Data Chair"
  organization: "1st International Workshop on Neurophysiological Intelligence for Human-Aware Multimedia (NeuroMM), co-located with ACM Multimedia 2026"
  period: "2026"
  link: "https://2026.neuromm.org/"
  note: ""
